import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/widgets.dart';
import 'package:learning_app/app/app_state.dart';
import 'package:provider/provider.dart';

/// The short UI sound effects Mimi plays alongside haptics.
///
/// Assets are synthesized tones generated by `tools/build_sfx_assets.py` —
/// see `assets/sfx/CREDITS.md` for why (no real CC0 library was reachable
/// from this sandbox) and what each file is.
enum SfxSound { correct, incorrect, celebration, tap }

/// Plays [SfxSound]s, muted whenever the learner has sound turned off.
///
/// One [AudioPlayer] per sound (rather than one shared player) so that a
/// fast double-tap (e.g. two quick correct answers) doesn't cut a sound off
/// to restart it — each clip can overlap its own previous play.
class SoundService {
  SoundService();

  static const _paths = {
    SfxSound.correct: 'sfx/correct.wav',
    SfxSound.incorrect: 'sfx/incorrect.wav',
    SfxSound.celebration: 'sfx/celebration.wav',
    SfxSound.tap: 'sfx/tap.wav',
  };

  final Map<SfxSound, AudioPlayer> _players = {};

  AudioPlayer _playerFor(SfxSound sound) => _players.putIfAbsent(sound, () {
        final player = AudioPlayer(playerId: 'sfx_${sound.name}');
        player.setReleaseMode(ReleaseMode.stop);
        player.setPlayerMode(PlayerMode.lowLatency);
        return player;
      });

  /// Plays [sound] unless [enabled] is false (pass the learner's current
  /// `soundEnabled` setting — the same flag that already gates TTS
  /// playback, in `Réglages`). Failures are swallowed: a missing/unplayable
  /// audio asset must never crash or block the interaction it decorates.
  Future<void> play(SfxSound sound, {required bool enabled}) async {
    if (!enabled) return;
    try {
      await _playerFor(sound).play(AssetSource(_paths[sound]!), volume: 0.7);
    } catch (error) {
      debugPrint('SoundService: could not play ${sound.name}: $error');
    }
  }

  Future<void> dispose() async {
    for (final player in _players.values) {
      await player.dispose();
    }
    _players.clear();
  }
}

/// Convenience wrapper around `context.read<SoundService>()` used at every
/// interaction site — looks up the learner's `soundEnabled` setting and
/// plays [sound] in one call, and never throws: widget tests (and any
/// widget built without the app's real Provider tree above it) simply get
/// silence instead of a `ProviderNotFoundException`.
void playSfx(BuildContext context, SfxSound sound) {
  try {
    final soundOn = context.read<LearningController>().soundEnabled;
    context.read<SoundService>().play(sound, enabled: soundOn);
  } catch (_) {}
}
