#!/usr/bin/env python3
"""Generates Mimi's UI sound effects as small synthesized WAV files.

No network access is used or required: every sound here is a short,
programmatically synthesized tone (sine/triangle waves with a simple
envelope), not a downloaded or recorded sample. That means there is no
license to track and no attribution to give -- the bytes are generated by
this script and are entirely original.

This is a deliberate substitute for sourcing real CC0 sound effects (e.g.
from freesound.org): this sandbox's egress proxy blocks connections to
freesound.org and other asset CDNs (organization policy), so downloading a
real library was not possible. Rather than ship no sound at all, this script
produces clean, tasteful, on-brand tones instead -- short, non-harsh,
major-interval blips that match Mimi's warm/playful identity without
resembling a generic OS chime.

Usage (from the repository root):

    python3 tools/build_sfx_assets.py

Writes frontend/assets/sfx/*.wav. These are generated artifacts: edit this
script and re-run rather than hand-editing the WAV files.
"""

from __future__ import annotations

import math
import os
import struct

SAMPLE_RATE = 44100
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend", "assets", "sfx")


def _note(freq: float, dur: float, amp: float, wave: str = "sine") -> list[float]:
    """Returns float samples in [-1, 1] for one tone with a short
    attack/decay envelope so it never clicks."""
    n = int(SAMPLE_RATE * dur)
    samples = []
    attack = min(0.012, dur * 0.25)
    release = min(0.06, dur * 0.5)
    for i in range(n):
        t = i / SAMPLE_RATE
        if wave == "triangle":
            phase = (t * freq) % 1.0
            v = 4 * abs(phase - 0.5) - 1
        else:
            v = math.sin(2 * math.pi * freq * t)
        if t < attack:
            env = t / attack
        elif t > dur - release:
            env = max(0.0, (dur - t) / release)
        else:
            env = 1.0
        samples.append(v * amp * env)
    return samples


def _mix(*layers: tuple[float, list[float]]) -> list[float]:
    """layers: (start_time, samples) pairs; mixes them onto one buffer."""
    total_len = max(int(round(s * SAMPLE_RATE)) + len(sm) for s, sm in layers)
    buf = [0.0] * total_len
    for start, sm in layers:
        offset = int(round(start * SAMPLE_RATE))
        for i, v in enumerate(sm):
            buf[offset + i] += v
    peak = max((abs(v) for v in buf), default=1.0) or 1.0
    if peak > 0.92:
        buf = [v / peak * 0.92 for v in buf]
    return buf


def _write_wav(path: str, samples: list[float]) -> None:
    n = len(samples)
    data = struct.pack(
        "<%dh" % n, *(int(max(-1.0, min(1.0, v)) * 32767) for v in samples)
    )
    with open(path, "wb") as f:
        f.write(b"RIFF")
        f.write(struct.pack("<I", 36 + len(data)))
        f.write(b"WAVE")
        f.write(b"fmt ")
        f.write(struct.pack("<IHHIIHH", 16, 1, 1, SAMPLE_RATE, SAMPLE_RATE * 2, 2, 16))
        f.write(b"data")
        f.write(struct.pack("<I", len(data)))
        f.write(data)


def build_correct() -> None:
    """Correct answer: a bright, quick ascending major arpeggio
    (C6 -> E6 -> G6), like a small friendly "ding-ding-ding"."""
    samples = _mix(
        (0.00, _note(1046.5, 0.11, 0.5, "sine")),  # C6
        (0.05, _note(1318.5, 0.13, 0.45, "sine")),  # E6
        (0.10, _note(1568.0, 0.20, 0.4, "sine")),  # G6
    )
    _write_wav(os.path.join(OUT_DIR, "correct.wav"), samples)


def build_incorrect() -> None:
    """Gentle error: a soft, low, short two-note falling interval.
    Deliberately not harsh/buzzy -- Mimi never scolds."""
    samples = _mix(
        (0.00, _note(392.0, 0.10, 0.35, "triangle")),  # G4
        (0.07, _note(329.6, 0.16, 0.30, "triangle")),  # E4
    )
    _write_wav(os.path.join(OUT_DIR, "incorrect.wav"), samples)


def build_celebration() -> None:
    """Streak / milestone celebration: a short ascending arpeggio with a
    final held sparkle -- bigger and longer than the correct-answer chime."""
    samples = _mix(
        (0.00, _note(523.3, 0.10, 0.45, "sine")),  # C5
        (0.08, _note(659.3, 0.10, 0.45, "sine")),  # E5
        (0.16, _note(784.0, 0.10, 0.45, "sine")),  # G5
        (0.24, _note(1046.5, 0.30, 0.5, "sine")),  # C6 (held)
        (0.24, _note(1568.0, 0.30, 0.25, "sine")),  # G6 sparkle layer
    )
    _write_wav(os.path.join(OUT_DIR, "celebration.wav"), samples)


def build_tap() -> None:
    """Soft tap/confirm: a very short, quiet single blip for low-stakes taps
    (e.g. selecting an option) that shouldn't compete with correct.wav."""
    samples = _mix((0.00, _note(880.0, 0.05, 0.28, "sine")))
    _write_wav(os.path.join(OUT_DIR, "tap.wav"), samples)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    build_correct()
    build_incorrect()
    build_celebration()
    build_tap()
    for name in ("correct.wav", "incorrect.wav", "celebration.wav", "tap.wav"):
        path = os.path.join(OUT_DIR, name)
        print(f"wrote {path} ({os.path.getsize(path)} bytes)")


if __name__ == "__main__":
    main()
